### ISSUE TITLE
NPX execution in CI eats a lot of time

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#771]
22% of the time spent [on this VM job](https://github.com/ethereumjs/ethereumjs-vm/blob/master/.github/workflows/vm-build.yml#L34-L37) is due to redundant `npx` downloads. And this is one of the most optimistic examples.

We should bust them from our CIs and make overall simplification of the CI commands

from [this](https://github.com/ethereumjs/ethereumjs-vm/blob/master/.github/workflows/blockchain-build.yml#L25-L28):
```yaml
- run: npx lerna bootstrap --scope @ethereumjs/vm --ignore-scripts --include-dependencies --no-ci
- run: npx lerna run build --scope @ethereumjs/vm --include-dependencies
- run: npx lerna run test:state:selectedForks --scope @ethereumjs/vm
- run: npx lerna run coverage --scope @ethereumjs/vm
```

to target syntax:
```yaml
- run: npm run bootstrap @ethereumjs/vm
- run: npm run build:withDeps @ethereumjs/vm
- run: npm run test @ethereumjs/vm
- run: npm run coverage @ethereumjs/vm
```
